language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
   sources:
    - ubuntu-toolchain-r-test
    update: true
    packages:
      - cmake
      - g++-7

script:
  - cd hello_world_application
  - cmake -H. -B _build
  - cmake --build _build --target hello_world
  - cd ..
  - cd solver_application
  - cmake -H. -B _build
  - cmake --build _build --target solver
